- Fitness/Controllers/HomeController.swift
- Fitness/Models/Gym.swift
- Fitness/Views/Cells/AllGymsCell.swift
- Fitness/Views/Cells/TodaysClassesCell.swift
-Open gyms will now appear before closed gyms
> Sorted gyms in the Home VC

- .swiftlint.yml
- Fitness.xcodeproj/project.pbxproj
- Fitness/API.swift
- Fitness/Controllers/FilterViewController.swift
- Fitness/graphql/query.graphql
- Podfile.lock
I fixed all the codegen issues.
You must do:
1. Make sure you don't have any versions of apollo by first doing `npm uninstall -g apollo`
2. Install version 1.8 `npm i -g apollo@1.8`
No need for node_modules/ in the actual directory.
run the app and boom it works. If nothing shows up in API.swift, it is bc your query is malformed. The build script won't tell it is, but it is.
Checkmate apollo.
> fixed apollo codegen issues

- Fitness/Base.lproj/LaunchScreen.storyboard
- Fitness/Controllers/ClassListViewController.swift
- Fitness/Controllers/FilterViewController.swift
- Fitness/Controllers/HomeController.swift
- Fitness/Views/Cells/ClassListCell.swift
- Fitness/Views/Cells/GymsCell.swift
- Fitness/Views/Headers/HomeScreenHeaderView.swift
> Update and fix various ui elements

- Fitness.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- Fitness/Controllers/FavoritesViewController.swift
- Fitness/Controllers/OnboardingViewController.swift
- Podfile
- Podfile.lock
Fixed master, some issues with the Onboarding VC and a crash in favorites
> added fixes for testflight

- Fitness/Controllers/ClassDetailViewController.swift
- Fitness/Controllers/FavoritesViewController.swift
- Fitness/Controllers/GymDetailViewController.swift
- Fitness/Views/Cells/ClassListCell.swift
- Implemented Next Sessions section
- Fixed layout issues
- Misc UI tweaks & bug fixes
> Next sessions

- Constants.swift
- Fitness.xcodeproj/project.pbxproj
- Fitness/Controllers/ClassDetailViewController.swift
- Fitness/Controllers/ClassListViewController.swift
- Fitness/Controllers/FilterViewController.swift
- Fitness/Controllers/GymDetailViewController.swift
- Fitness/Controllers/HomeController.swift
- Fitness/Extensions/UIFont+Shared.swift
- Fitness/Views/Headers/TodaysClassesHeaderView.swift
Still waiting to get the images from design for the back/favorite buttons on light background in the detail view, but wanted to get this reviewed, I'll change them before merging!!
Changes:
- Disappearing search bar fixed
- Sorted instructors/class names in filter screen
- Made the selected day in the class list screen bold
- Resolved a spacing issue on the home screen
- Detail view back/favorite buttons adjust color based on background color
- Header images in the detail views expand when the scrollview is pulled down
- Added ‘view all’ button to today’s classes header in the home screen
- Small style fixes
> Bug fixes and UI touch ups

- Fitness/Controllers/GymDetailViewController.swift
- Push class detail view's in gym detail view
- Highlight animations in gym detail
- Class cells now have their room location
> Push class detail view's in gym detail view

- Fitness/Controllers/ClassDetailViewController.swift
- Fitness/Models/Gym.swift
- Podfile
- Podfile.lock
- Tweaks in share feature
- Simplified some networking stuff
> Minor design and networking changes

- LICENSE
@kevinchan159 (@kevinchan) this repo should require 2 approving reviews
> Add MiT license

- Uplift/Controllers/ClassListViewController.swift
Sort the GymClassInstances returned by backend by ascending start time in ClassListViewController.
Change: Use `sorted` to sort classes by start time.
Result: Classes are sorted by start time.
Verified visually.
Addresses #183
> Sort classes by start time in the Classes tab 

- Uplift.xcodeproj/project.pbxproj
- Uplift/Extensions/String+Shared.swift
- Uplift/Views/GymDetail/Facilities/PriceInformationView.swift
Implements the view to be used to display price information for a facility. In the current designs, this is only utilized by the Bowling Lanes facility. 
**Information is currently hard coded specifically for the bowling lanes since it's not possible to parse the right information from the backend model.**
Added `PriceInformationView` for the new view.
Screenshot embedded in a random view controller:
> Create view for price information

- Podfile.lock
- Uplift/Models/Gym.swift
- Uplift/graphql/gymQueries.graphql
Added facilities to what is returned by the GetGymByID query so it is consistent with getGyms query
Added to the graphql query and edited the Gym model to include facilities
^^
Tested the graphql query in iGraphql and printed out the contents of `facilities` to see if it was not empty, and contained correct information
> Add Facilities to getGymByID query

- Podfile.lock
- Uplift.xcodeproj/project.pbxproj
- Uplift/Controllers/GymDetailViewController.swift
- Uplift/Views/GymDetail/Facilities/PriceInformationCell.swift
- Uplift/Views/GymDetail/Facilities/PriceInformationView.swift
Changes `PriceInformationView` to be a subclass of `UICollectionViewCell` and renames it to `PriceInformationCell`. 
Adds a `configure` function so that the cell can be configured for data retrieved from the backend. 
Also adds a `getHeight` function to be used when the cell is placed in a collection view.
Changes the constraints so that the height of the view is dynamic, depending on the number of items to be displayed.
Added the collection view cell to an existing collection view and tested with different number of items to display.
Integrate into overall facilities cole
#199 
<details>
<summary>Two items</summary>
</details>
<details>
<summary>Three items</summary>
</details>
> Change PriceInformationView to collection view cell

- Uplift/Controllers/GymDetailViewController.swift
- Uplift/Views/Cells/FacilitiesDropdownCell.swift
- Uplift/Views/Dropdown/DropdownView.swift
- Uplift/Views/GymDetail/AdditionalInfoView.swift
- Uplift/Views/GymDetail/Facilities/FacilitiesHoursCell.swift
- Uplift/Views/GymDetail/GymDetailFacilitiesCell.swift
- Uplift/Views/GymDetail/GymDetailTimeInfoView.swift
- Uplift/Views/GymDetail/GymDetailWeekView.swift
Fixes issue where changing day on calendar view sometimes crashes.
Cleaned up the logic that is called when a new day is selected and removed unnecessary closures.
Ran and tested facility dropdowns.
Test more and ship!
> Fixes calendar change index logic

- Uplift/Views/FacilitiesDropdownHeaderView.swift
<details>
<summary>Screen Shot Name</summary>
</details>
> Minor refactor

- Uplift/Controllers/FavoritesViewController.swift
<details>
<summary>Screen Shot Name</summary>
</details>
> Fix tab color change on select after Browse Classes

- Uplift/Controllers/HomeViewController+Extensions.swift
<details>
<summary>Screen Shot Name</summary>
</details>
> Fix selected vc

- Uplift.xcodeproj/project.pbxproj
- Uplift/Controllers/FavoriteGymsController.swift
- Uplift/Controllers/GymDetailViewController.swift
- Uplift/Controllers/HomeViewController+Extensions.swift
- Uplift/Supporting/ClientStrings.swift
- Uplift/Supporting/Constants.swift
- Uplift/Views/GymDetail/GymDetailFacilitiesCell.swift
<details>
<summary>Screen Shot Name</summary>
</details>
> Add facilities label

- Uplift/Controllers/GymDetailViewController.swift
Fixes a typo in `GymDetailViewController` that was causing an error
> Fixed typo

- Uplift.xcodeproj/project.pbxproj
- Uplift/Controllers/SportsFeedViewController.swift
- Uplift/Controllers/SportsFormViewController.swift
- Uplift/Extensions/Date+Shared.swift
- Uplift/Models/Post.swift
- Uplift/Supporting/ClientStrings.swift
- Uplift/Supporting/Constants.swift
- Uplift/Views/Dropdown/DropdownHeaderView.swift
- Uplift/Views/Headers/SportsFeedHeaderView.swift
- Uplift/Views/PaddedTextField.swift
- Uplift/Views/SportsForm/SportsFormBubbleCollectionViewCell.swift
- Uplift/Views/SportsForm/SportsFormBubbleInputTableViewCell.swift
- Uplift/Views/SportsForm/SportsFormBubbleTableViewCell.swift
- Uplift/Views/SportsForm/SportsFormNameCollectionViewCell.swift
- Uplift/Views/SportsForm/SportsFormPlayersCollectionViewCell.swift
- Uplift/Views/SportsForm/SportsFormTimeCollectionViewCell.swift
Complete UI for "Create a Game" page with date/time pickers for date/time input.
Compiles and runs.
> Create sports form to add pickup game.

- Podfile.lock
- Uplift.xcodeproj/project.pbxproj
- Uplift.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- Uplift/AppDelegate.swift
- Uplift/Controllers/HomeViewController+Extensions.swift
- Uplift/Controllers/HomeViewController.swift
- Uplift/Controllers/TabBarController.swift
- Uplift/Views/Headers/HomeSectionHeaderView.swift
- Uplift/Views/Home/GymsListCell.swift
- package.json
* Removed "Looking For" Section
* Removed TabBar
* Made rootVC a Navigation VC
* Added Mark comments addressing the slight changes I made in the file to remember to change them back when we begin adding the features I took out of the app originally
* Fix the bug where the tab bar appears after adding gyms
<details>
<summary>Home Page</summary>
</details>
> Uplift Initial Revive Updates

- Uplift.xcodeproj/project.pbxproj
- Uplift/Controllers/HomeViewController+Extensions.swift
- Uplift/Views/Footers/GymCellFooter.swift
- Uplift/Views/Headers/GymHoursHeaderView.swift
- Uplift/Views/Home/GymListItemCell.swift
- Uplift/Views/Home/GymsListCell.swift
Created the shape of the cell body and attached an image to each cell, while also adding a cell footer.
- Created new file GymCellFooter to take care of the footer for each cell
- Modified existing cell code in the GymListItemCell file to manage how the cells look
- ran the cells on multiple devices (iphone 14 and 13)
- Need to add feature icons and distance away from gym to cell footer once backend gives me those endpoints
- need to update current gym capacity status and gym capacity counts once backend gets me the endpoints
<details>
<summary>Home Screen</summary>
</details>
> Progress on gym cell changes

- Uplift/Controllers/HomeViewController+Extensions.swift
- Uplift/Controllers/HomeViewController.swift
- Uplift/Views/Home/ActivityListItemCell.swift
- Uplift/graphql/gymQueries_old.graphql.txt
- schema.graphqls
There are two goals of this PR: the first is to get the homepage's collection views fixed to a presentable state, the second is to clean up the home page code and remove unused code.
Side Note: I also added the new graphql schema for future networking purposes (not connected to the project yet). 
For the general home page, I fixed the collection view reloading so that it properly loads the views when returning a networking call. I also updated the shadow code for the activity cells to make it match the Figma more accurately. 
Many of the extra collection view sections that we were not using have been deleted from the home page keeping only those that we need (Today's classes, Your Activities, and Gyms). 
There was no significant testing other than checking that it looks more similar to …
> Fix homepage view bugs

- Uplift/Views/Home/GymListItemCell.swift
Update the home screen card to match design (add shadow and corner radius)
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Update home screen cards to match design

- Uplift.xcodeproj/project.pbxproj
- Uplift/AppDelegate.swift
- Uplift/Controllers/Gym Detail/GymDetailViewController+Extensions.swift
- Uplift/Controllers/Gym Detail/GymDetailViewController.swift
- Uplift/Models/GymManager.swift
- Uplift/Views/GymDetail/Hours/GymDetailHoursCell.swift
- Uplift/Views/GymDetail/TabbedView/GymDetailFitnessCenterViewController.swift
- Uplift/Views/GymDetail/TabbedView/GymDetailTabbedControl.swift
- Uplift/Views/GymDetail/TabbedView/GymDetailTabbedControllerCell.swift
- Uplift/Views/TabbedView/TabbedControl.swift
- Uplift/Views/TabbedView/TabbedViewController.swift
This PR is the code for the tabbed controller on the detail page.
There are a few files added to make the idea of a tabbed controller more generic. 
This ViewController is responsible for taking in subviewcontrollers (kinda like a tab bar controller), and a TabbedController object and facilitating navigation between the view controllers using the tabbed controller in a very similar way that a tab bar controller would.
This is the tab bar equivalent of this system. Its represented as a protocol so any use case can implement its own style of tabs but it is responsible for choosing the options of which tab/view controller is being displayed.
The gym detail implementation of this: just has some buttons and an accented yellow for which one is selected.
This is the cell that puts everything …
> Implement Tabbed Controller
